print("Digite su rut: ")
irut = input()
print("Digite su nombre y apellido: ")
inombre = input()
print("Digite su dirección: ")
idirec = input()
print("Digite su correo electrónico: ")
icorreo = input()
print("\n##############################\n")
print("¡Hola! "+inombre+", tu rut es: "+irut+"\nVives en: "+idirec+"\nTu correo electrónico es: "+icorreo)